apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: entrycam
spec:
  type: bindings.azure.eventhubs
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: dapr-traffic-control-iothub
      key:  iothubconnectionstring
  - name: consumerGroup
    value: "trafficcontrolservice"
  - name: storageAccountName
    value: "sarutzscodaprdemoci"
  - name: storageAccountKey
    value: "KJmbMNy9h0A1wenOmtwzJaB3zSI1+tV4nHndvwjzvZs6kVLSh9nkOtFjh3+pqkJ8Pz3PzhhG79e6+AStP9DykA=="
  - name: storageContainerName
    value: "trafficcontrol-entrycam"
auth:
  secretStore: secret-store
scopes:
- trafficcontrolservice


---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: exitcam
spec:
  type: bindings.azure.eventhubs
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: dapr-traffic-control-iothub
      key:  iothubconnectionstring
  - name: consumerGroup
    value: "trafficcontrolservice"
  - name: storageAccountName
    value: "sarutzscodaprdemoci"
  - name: storageAccountKey
    value: "KJmbMNy9h0A1wenOmtwzJaB3zSI1+tV4nHndvwjzvZs6kVLSh9nkOtFjh3+pqkJ8Pz3PzhhG79e6+AStP9DykA=="
  - name: storageContainerName
    value: "trafficcontrol-exitcam"
auth:
  secretStore: secret-store
scopes:
- trafficcontrolservice