trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'FineCollectionService - BUILD'
  
variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'Demo Account'
  resourceGroupName: 'rutzsco-dapr-demo'
  location: 'eastus'
  environment: 'rutzsco-dapr-demo-aca-ci'
  containerImage: 'rutzscolabcr.azurecr.io/dapr-hack/vehicleregistrationservice:$(resources.pipeline.build.runName)'
  templateFile: 'build/Infrastructure/aca/main.bicep'
  acrName: 'rutzscolabcr'
  acrUsername: 'rutzscolabcr'
pool:
  vmImage: $(vmImageName)

steps:

- task: AzureCLI@2
  displayName: Deploy FineCollectionService
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters containerImage=$(containerImage) envName=$(environment) acrName=$(acrName) acrUsername=$(acrUsername) acrPassword=$(acrPassword) > outputs.json