trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'FineCollectionService - BUILD'
  
variables:
  - group: dapr-traffic-control-demo
  - name: containerImage
    value: '$(acrName).azurecr.io/dapr-hack/finecollectionservice:$(resources.pipeline.build.runName)'
  - name: templateFile
    value: '$(Pipeline.Workspace)/build/Deploy/main.bicep'
pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureCLI@2
  displayName: Deploy FineCollectionService
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters containerImage=$(containerImage) envName=$(environment) acrName=$(acrName) acrUsername=$(acrUsername) acrPassword=$(acrPassword) > outputs.json