kind: Service
apiVersion: v1
metadata:
  name: finecollectionservice 
  labels:
    app: finecollectionservice
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3500
  selector:
    app: finecollectionservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finecollectionservice
  labels:
    app: finecollectionservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finecollectionservice
  template:
    metadata:
      labels:
        app: finecollectionservice
        aadpodidbinding: mi-aks-dapr-ussc-demo
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "finecollectionservice"
        dapr.io/app-port: "6001"
        dapr.io/log-level: "debug"
        dapr.io/sidecar-cpu-request: "100m"
        dapr.io/sidecar-memory-request: "250Mi"
        dapr.io/sidecar-cpu-limit: "300m"
        dapr.io/sidecar-memory-limit: "1000Mi"
        dapr.io/config: "zipkin"
    spec:
      containers:
      - name: finecollectionservice
        image: crdaprusscdemo.azurecr.io/finecollectionservice:assignment08
        ports:
        - containerPort: 6001
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 200Mi
        livenessProbe:
          httpGet:
            path: v1.0/healthz
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds : 5
          failureThreshold : 3
        readinessProbe:
          httpGet:
            path: v1.0/healthz
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds : 5
          failureThreshold: 3

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finecollectionservice
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: finecollectionservice.e13e6fb6d2534a41ae60.southcentralus.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: finecollectionservice
            port: 
              number: 80
              