apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finecollectionservice
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: finecollectionservice.e13e6fb6d2534a41ae60.southcentralus.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: finecollectionservice
            port: 
              number: 80
              