name: 0.1.$(Rev:r)
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Infrastructure/aca/*
    
variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'Demo Account'
  resourceGroupName: 'rutzsco-dapr-demo-aca'
  location: 'eastus'
  environment: 'rutzsco-dapr-demo-aca'
  containerImage: 'rutzscolabcr.azurecr.io/dapr-hack/vehicleregistrationservice:latest'
  templateFile: 'Infrastructure/aca/main.bicep'
  acrName: 'rutzscolabcr'
  acrUsername: 'rutzscolabcr'
pool:
  vmImage: $(vmImageName)

steps:

- task: AzureCLI@2
  displayName: Deploy Dapr Components
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az group create --name $(resourceGroupName) --location $(location)  
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters envName=$(environment) acrName=$(acrName) acrUsername=$(acrUsername) acrPassword=$(acrPassword) redisPassword=$(redisPassword) servicebusconnectionstring='$(servicebusconnectionstring)' logicAppEmailUrl='$(logicAppEmailUrl)' > outputs.json