parameters: 
- name: appName
  default: ''
- name: environment
  default: ''
- name: azureSubscription
  default: ''
- name: resourceGroupName
  default: ''
- name: location
  default: ''
- name: templateFile
  default: ''

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: DeployResources
  displayName: Initialize Deploy Resources
  environment: ${{ parameters.environment }}

- job: DeployResourcesJob
  displayName: Deploy Resources
  variables:
  - name: environment
    value: ${{ parameters.environment }}
  - name: environmentLower
    value: ${{ lower(parameters.environment) }}
  - name: templateFile
    value: '$(Pipeline.Workspace)/s/Infrastructure/bicep/main.bicep'

  steps:
   - bash: |
     ls
     echo $(Build.Repository.LocalPath)
     echo $(Build.SourcesDirectory)
     echo $(Build.SourceVersionMessage)

     cd $(Build.Repository.LocalPath)
     ls
   displayName: 'Display Variables'

