name: 0.1.$(Rev:r)
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Infrastructure/bicep/*
    
variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'Demo Account'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    appName: 'rutzsco-dapr-demo'
    environment: 'aks'
    azureSubscription: $(azureSubscription)
    location: 'eastus'
    resourceGroupName: rutzsco-dapr-demo-aks'
- template: azure-release-pipelines-stage-template.yml
  parameters:
    appName: 'rutzsco-dapr-demo'
    environment: 'aca'
    azureSubscription: $(azureSubscription)
    location: 'eastus'
    resourceGroupName: 'rutzsco-dapr-demo-aca'
      
      