name: 0.1.$(Rev:r)
pool:
  vmImage: 'ubuntu-latest'

# ----------------------------------------------------------------------------------------------------
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Infrastructure/bicep/*
    
variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'Demo Account'

stages:
  - stage: AKS
    displayName: Deploy AKS
    jobs:
    - template: azure-pipelines-core-deploy-template.yml
      parameters:
        appName: 'rutzsco-dapr-demo'
        environment: 'aks'
        azureSubscription: $(azureServiceConnection)
        location: 'eastus'
        resourceGroupName: 'rutzsco-dapr-demo-aks'
        templateFile: '$(Build.Repository.LocalPath)/Infrastructure/bicep/main.bicep'
  - stage: ACA
    displayName: Deploy ACA
    jobs:
    - template: azure-pipelines-core-deploy-template.yml
      parameters:
        appName: 'rutzsco-dapr-demo'
        environment: 'aca'
        azureSubscription: $(azureServiceConnection)
        location: 'eastus'
        resourceGroupName: 'rutzsco-dapr-demo-aca'
        templateFile: '$(Build.Repository.LocalPath)/Infrastructure/bicep/main.bicep'