name: 0.1.$(Rev:r)
# ----------------------------------------------------------------------------------------------------
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Infrastructure/bicep/*
    
variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'Demo Account'

stages:
- template: azure-pipelines-core-deploy-template.yml
  parameters:
    stageName: 'aks'
    appName: 'rutzsco-dapr-demo'
    environment: 'aks'
    azureSubscription: $(azureServiceConnection)
    location: 'eastus'
    resourceGroupName: 'rutzsco-dapr-demo-aks'
    templateFile: '$(Build.Repository.LocalPath)/Infrastructure/bicep/main.bicep'
