parameters: 
- name: stageName
  default: ''
- name: appName
  default: ''
- name: environment
  default: ''
- name: azureSubscription
  default: ''
- name: resourceGroupName
  default: ''
- name: location
  default: ''
- name: templateFile
  default: ''

# ----------------------------------------------------------------------------------------------------
stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'ubuntu-latest'
  
      strategy:
        runOnce:
          deploy:
  
            steps:           
            - task: AzureCLI@2
              displayName: 'Create Resource Group'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: az group create --name ${{ parameters.resourceGroupName }} --location ${{ parameters.location }}

            - task: AzureCLI@2
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                 ls
                 az group create --name ${{ parameters.resourceGroupName }} --location ${{ parameters.location }} 
                 az deployment group create --resource-group ${{ parameters.resourceGroupName }} --template-file ${{ parameters.templateFile }} --parameters appName=${{ parameters.appName }} environment=${{ parameters.environment }} > outputs.json
