parameters: 
- name: appName
  default: ''
- name: environment
  default: ''
- name: azureSubscription
  default: ''
- name: resourceGroupName
  default: ''
- name: location
  default: ''
- name: templateFile
  default: ''

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: DeployResources
  displayName: Initialize Deploy Resources
  environment: ${{ parameters.environment }}

- job: DeployResourcesJob
  displayName: Deploy Resources
  variables:
  - name: environment
    value: ${{ parameters.environment }}
  - name: environmentLower
    value: ${{ lower(parameters.environment) }}
  - name: templateFile
    value: '$(Pipeline.Workspace)/s/Infrastructure/bicep/main.bicep'

  steps:
  
  - task: AzureCLI@2
     displayName: 'Create Resource Group'
     inputs:
       azureSubscription: ${{ parameters.azureSubscription }}
       scriptType: bash
       scriptLocation: inlineScript
       inlineScript: az group create --name ${{ parameters.resourceGroupName }} --location ${{ parameters.location }}


