apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trafficcontrolservice
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: trafficcontrolservice.e13e6fb6d2534a41ae60.southcentralus.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: trafficcontrolservice
            port: 
              number: 80