trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/FineCollectionService/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  rootDirectory: 'src/FineCollectionService'
  dockerRegistryServiceConnection: 'aefdd2ab-f2b0-4625-ace6-1625a6ed13ec'
  dockerImageRepository: 'dapr-hack/FineCollectionService'
  dockerFilePath: '$(Build.SourcesDirectory)/$(rootDirectory)/Dockerfile'
  dockerImageTag: '$(Build.BuildNumber)'

steps:

- task: Docker@2
  displayName: 'Container - Build and push'
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(dockerImageRepository)'
    command: 'buildAndPush'
    Dockerfile: '$(dockerFilePath)'
    buildContext: '$(Build.SourcesDirectory)/$(rootDirectory)/'
    tags: |
      $(dockerImageTag)
      latest

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/$(rootDirectory)/deploy/'
    artifact: 'Deploy'
    publishLocation: 'pipeline'