apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secret-store-akv
  namespace: dapr-traffic-control
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: "rutzsco-dapr-demo-aks"
  - name: azureTenantId
    value: "TBD"
  - name: azureClientId
    value: "TBD"
  - name: azureClientSecret
    secretKeyRef:
      name: dapr-traffic-control-akvsspn
      key:  azureKVSPNClientSecret
auth:
  secretStore: secret-store