apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: exitcam
  namespace: dapr-traffic-control
spec:
  type: bindings.azure.eventhubs
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: dapr-traffic-control-iothub
      key:  iothubconnectionstring
  - name: consumerGroup
    value: "trafficcontrolservice"
  - name: storageAccountName
    value: "rutzscodaprdemocisa"
  - name: storageAccountKey
    secretKeyRef:
      name: dapr-traffic-control-iothub-sa
      key:  iothubstorageaccountkey
  - name: storageContainerName
    value: "trafficcontrol-exitcam"
auth:
  secretStore: secret-store
scopes:
- trafficcontrolservice