apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: collectfine-subscription
  namespace: dapr-traffic-control
spec:
  topic: collectfine
  route: /collectfine
  pubsubname: pubsub
scopes:
- finecollectionservice